language: ruby

services:
  - docker

env:
  global:
    - secure: lFzDBnOmW6wWvAati2cj9AbfTFF4mzbkSXtFvptAgpwGpAiBHlY/I9qkzfESNPRKWY8KkF37d60KGm0xwAuSv1vr+GEsJP/b0SuXuVZ2hkYJYlicE3wd0LtT5jRhwmorp7WUaRfl0iHtGQv+K43TYFebUXi/8MIsZFU/sdE2WOo=

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - script/build $TRAVIS_COMMIT
  - script/deploy
after_success:
  - script/deploy
