safe:        false
url:         http://localhost:4000
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
permalink:   date
exclude:     [bin, tasks, docs, Gemfile, Gemfile.lock, README.md]

sass:
    sass_dir: css