safe:        false
url:         http://enricogenauck.de
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
permalink:   date
exclude:     [bin, tasks, docs, Gemfile, Gemfile.lock, README.md, vendor]

sass:
    sass_dir: css

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
